import {createGame,getLegalMoves,chooseMove,play,pass,sortHand,cardLabel,comboLabel,classify,canBeat} from './engine.js';
const $=s=>document.querySelector(s), names=['你','小岚','阿曜 · 搭档','星野'], icons=['♠','☾','✦','◇'];
let settings=read('settings',{difficulty:'normal',sound:true,speed:'normal'}), stats=read('stats',{rounds:0,wins:0}), match=read('match',{levels:[2,2],level:2}), state=null,mode='classic',selected=new Set(),timer=null,toastTimer=null,hintIndex=0,auto=false,paused=false,reverse=false,roundSaved=false,audio=null;
function read(key,fallback){try{return JSON.parse(localStorage.getItem('guandan-'+key))??fallback}catch{return fallback}}
function save(key,data){try{localStorage.setItem('guandan-'+key,JSON.stringify(data))}catch{}}
function persist(){if(state)save('game',{state,mode,roundSaved});else try{localStorage.removeItem('guandan-game')}catch{}}
function sound(kind='tap'){if(!settings.sound)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.type='sine';o.frequency.setValueAtTime(kind==='win'?660:kind==='play'?400:300,audio.currentTime);o.frequency.exponentialRampToValueAtTime(kind==='win'?1100:180,audio.currentTime+.13);g.gain.setValueAtTime(.055,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);o.start();o.stop(audio.currentTime+.2)}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2300)}
function modal(html){clearTimeout(timer);$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){$('#modal').close();schedule()}
$('#modal-close').onclick=closeModal;$('#modal').addEventListener('close',schedule);
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
function rank(r){return({11:'J',12:'Q',13:'K',14:'A',15:'小王',16:'大王'})[r]||r}
function cardHTML(c,interactive=false){const red=c.suit==='H'||c.suit==='D'||c.rank===16,wild=c.suit==='H'&&c.rank===state.level,joker=c.rank>14,suit=({H:'♥',D:'♦',S:'♠',C:'♣',J:'✦'})[c.suit];return `<${interactive?'button':'div'} class="card ${red?'red':''} ${wild?'wild':''} ${c.rank===state.level?'level':''} ${joker?'joker':''} ${selected.has(c.id)&&interactive?'selected':''}" ${interactive?`data-card="${c.id}" aria-label="${cardLabel(c)}${wild?' 逢人配':''}" aria-pressed="${selected.has(c.id)}"`:''}>${rank(c.rank)}<span class="suit">${suit}</span>${!joker?`<span class="big-suit">${suit}</span>`:''}${wild?'<span class="wild-label">百搭</span>':''}</${interactive?'button':'div'}>`}
function statsUI(){$('#stat-rounds').textContent=stats.rounds;$('#stat-wins').textContent=stats.wins;$('#stat-rate').textContent=stats.rounds?Math.round(stats.wins/stats.rounds*100)+'%':'—'}
function start(m){mode=m;auto=false;roundSaved=false;selected.clear();reverse=false;hintIndex=0;state=createGame({level:m==='classic'?match.level:m==='quick'?2+Math.floor(Math.random()*13):2,difficulty:settings.difficulty,teamLevels:m==='classic'?match.levels:[2,2]});$('#lobby').hidden=true;$('#game').hidden=false;render();persist();sound();schedule()}
for(const btn of document.querySelectorAll('[data-mode]'))btn.onclick=()=>{if(state&&!state.result){modal('<div class="modal-eyebrow">YOUR TABLE IS WAITING</div><h2>还有一局没打完</h2><p>继续当前牌局，或放弃当前牌局重新开局。</p><button class="play-button wide" id="resume">继续牌局</button><button class="secondary wide" id="restart">开始新牌局</button>');$('#resume').onclick=()=>{closeModal();$('#lobby').hidden=true;$('#game').hidden=false;render();schedule()};$('#restart').onclick=()=>{closeModal();start(btn.dataset.mode)}}else start(btn.dataset.mode)};
function render(){if(!state)return;$('#mode-label').textContent={classic:'经典升级',quick:'快速开局',practice:'明牌练习'}[mode];$('#level-label').textContent=rank(state.level);$('#score-us').textContent=rank((state.teamLevels||match.levels)[0]);$('#score-them').textContent=rank((state.teamLevels||match.levels)[1]);$('#auto').textContent='托管 '+(auto?'开':'关');for(const seat of [1,2,3]){const place=state.finished.indexOf(seat),el=$('#seat-'+seat);el.classList.toggle('active',state.turn===seat&&!state.result);el.innerHTML=`<div class="avatar">${icons[seat]}</div><div class="seat-name">${names[seat]}<small>${seat===2?'与你同队':'对手'}</small><span class="remaining ${place>=0?'finish-badge':''}">${place>=0?['头游','二游','三游','末游'][place]:state.hands[seat].length+' 张'}</span></div>`}const trick=state.trick;$('#played').innerHTML=trick?`<div class="played-label">${names[trick.seat]}<b>${comboLabel(trick.combo)}</b></div><div class="played-cards">${trick.cards.map(c=>cardHTML(c)).join('')}</div>`:'<div class="played-label">新一轮 · 自由出牌</div>';$('#table-status').textContent=state.result?'本局结束':state.turn===0?(state.trick?'轮到你 · 接牌或不出':'轮到你 · 请领出一手牌'):names[state.turn]+' 正在思考…';$('#turn-status').textContent=state.finished.includes(0)?'已出完 · 观战中':state.turn===0?'● 轮到你':'';$('#hand-count').textContent=state.hands[0].length+' 张';renderHand();const mine=state.turn===0&&!state.result&&!auto;$('#pass').disabled=!mine||!state.trick;$('#hint').disabled=!mine;$('#play').disabled=state.result?false:!mine||selected.size===0;$('#play').innerHTML=state.result?'查看结算 ↗':'出牌 <span>↗</span>';$('#clear').disabled=selected.size===0;$('#sort').disabled=state.hands[0].length===0;selectionLabel()}
function renderHand(){let cards=sortHand(state.hands[0],state.level);if(reverse)cards=cards.slice().reverse();const width=$('#hand').clientWidth||350,small=window.innerWidth<=560&&window.innerHeight>560,cardWidth=small?43:window.innerHeight<=560?41:window.innerWidth<=800?49:55;let perRow=small?Math.ceil(cards.length/2):cards.length;perRow=Math.max(1,perRow);let overlap=Math.min(0,Math.floor((width-28-cardWidth)/(Math.max(1,perRow-1))-cardWidth));overlap=Math.max(-(cardWidth-16),overlap);$('#hand').style.setProperty('--card-overlap',overlap+'px');$('#hand').innerHTML=cards.map((c,i)=>`${small&&i===perRow?'<span style="flex-basis:100%;height:0"></span>':''}${cardHTML(c,true)}`).join('');for(const b of document.querySelectorAll('[data-card]'))b.onclick=()=>{if(state.turn!==0||state.result||auto)return toast('请等轮到你出牌');const id=b.dataset.card;selected.has(id)?selected.delete(id):selected.add(id);b.classList.toggle('selected',selected.has(id));b.setAttribute('aria-pressed',selected.has(id));$('#play').disabled=selected.size===0;$('#clear').disabled=selected.size===0;selectionLabel();sound()}}
function selectionLabel(){if(!selected.size){$('#selection-status').textContent='点击牌面选牌 · 红桃级牌可替代普通牌';return}const cards=state.hands[0].filter(c=>selected.has(c.id));const combo=classify(cards,state.level,state.trick?.combo);$('#selection-status').textContent=combo?`已选 ${cards.length} 张 · ${comboLabel(combo)}${state.trick&&!canBeat(combo,state.trick.combo)?' · 无法压过上家':''}`:`已选 ${cards.length} 张 · 暂不构成有效牌型`}
function move(ids,declaration=null){try{const cards=state.hands[state.turn].filter(c=>ids.includes(c.id));play(state,state.turn,ids,declaration);sound(cards.length>=4?'win':'play');selected.clear();hintIndex=0;render();persist();afterMove()}catch(e){toast(e.message||'这手牌暂时不能出')}}
function passTurn(){try{const seat=state.turn;pass(state,seat);selected.clear();hintIndex=0;render();toast(names[seat]+'：不出');persist();afterMove()}catch(e){toast(e.message)}}
function afterMove(){if(state.result){clearTimeout(timer);setTimeout(showResult,600)}else schedule()}
function schedule(){clearTimeout(timer);if(paused||document.hidden||$('#modal').open||$('#game').hidden||!state||state.result)return;if(state.turn===0&&!auto)return;timer=setTimeout(()=>{if(paused||$('#modal').open||!state||state.result)return;try{const m=chooseMove(state,state.turn);if(m)move(m.ids,m.combo);else passTurn()}catch(e){console.error(e);toast('牌局发生异常，请返回大厅重新开局')}},settings.speed==='fast'?450:950)}
$('#play').onclick=()=>state?.result?showResult():move([...selected]);$('#pass').onclick=passTurn;$('#clear').onclick=()=>{selected.clear();render()};$('#hint').onclick=()=>{const moves=getLegalMoves(state,0);if(!moves.length)return toast('没有能接的牌，可以选择不出');const m=moves[hintIndex++%moves.length];selected=new Set(m.ids);render();toast('建议：'+comboLabel(m.combo))};$('#sort').onclick=()=>{reverse=!reverse;renderHand()};$('#auto').onclick=()=>{auto=!auto;selected.clear();render();schedule();toast(auto?'已开启自动出牌':'已关闭托管')};$('#home').onclick=()=>{clearTimeout(timer);persist();$('#game').hidden=true;$('#lobby').hidden=false;statsUI()};
function showResult(){if(!state?.result)return;const r=state.result,win=r.winnerTeam===0;if(!roundSaved){stats.rounds++;if(win)stats.wins++;save('stats',stats);if(mode==='classic'){match=r.matchWon?{levels:[2,2],level:2}:{levels:r.teamLevels||state.teamLevels,level:r.nextLevel};save('match',match)}roundSaved=true;persist()}sound('win');modal(`<div class="modal-eyebrow">ROUND COMPLETE</div><div class="result-icon">${win?'✦':'♠'}</div><h2 class="result-title">${win?'默契制胜！':'再来，下一局！'}</h2><p style="text-align:center">${win?'你与阿曜赢下本局':'小岚与星野赢下本局'} · 升 ${r.upgrade} 级</p><div class="result-ranks">${r.order.map((s,i)=>`<div><b>${r.tiedLast?.includes(s)?'双下': ['头游','二游','三游','末游'][i]}</b>${names[s]}</div>`).join('')}</div><p>${mode==='classic'?`${r.matchWon?'打过 A，本场升级赛完成！下一场从 2 开始。':'下一局打 '+rank(r.nextLevel)+'。'}休闲升级模式不进行进贡、还贡。`:'换副牌，再试试新的配合。'}</p><button class="play-button wide" id="next-round">再来一局 ↗</button><button class="secondary wide" id="back-lobby">返回大厅</button>`);$('#next-round').onclick=()=>{closeModal();start(mode)};$('#back-lobby').onclick=()=>{closeModal();state=null;persist();$('#game').hidden=true;$('#lobby').hidden=false;statsUI()}}
$('#help').onclick=()=>modal(`<div class="modal-eyebrow">LEARN THE GAME</div><h2>一桌四人，两人一队</h2><p>你和对面的阿曜是搭档。两副扑克牌共 108 张，每人 27 张；率先出完手牌成为「头游」。</p><h3>出什么牌？</h3><ul><li>单张、对子、三张、三带二</li><li>顺子：恰好 5 张连续点数</li><li>连对：恰好 3 个连续对子</li><li>钢板：恰好 2 个连续三张</li><li>炸弹：4 张以上同点数；同花顺：5 张同花色连续牌；四王炸为最大牌</li></ul><h3>谁能压过谁？</h3><p>普通牌须同类型、同张数比较。点数从 2 到 A，级牌高于 A，小王、大王更大。顺子类按自然点数计算，A 可在最小端或最大端，不能绕回。炸弹压普通牌；张数更多的炸弹更大。同花顺压五张及以下炸弹，低于六张及以上炸弹。四王炸最大。</p><h3>♥ 红桃级牌 = 逢人配</h3><p>例如打 2 时，两张红桃 2 可替代任意普通牌组成牌型，但不能替代大小王。单张按级牌算。</p><h3>配合与升级</h3><p>一轮其余玩家都不出，最后出牌者重新领出；若该玩家已出完，由仍有牌的搭档接风。头游方获胜，搭档二游升 3 级、三游升 2 级、末游升 1 级。经典模式保存级数，A 必须实打，打 A 时搭档获二游或三游即可通关，重新从 2 开始；搭档末游则继续打 A。</p><p>这是离线休闲规则：无进贡/还贡、不支持真人联网，无金币或付费功能。「明牌练习」可在牌局记录中查看四家手牌。</p>`);
$('#settings').onclick=showSettings;function showSettings(){modal(`<div class="modal-eyebrow">MAKE IT YOURS</div><h2>你的牌桌，你做主</h2><div class="settings-row"><span>AI 难度（下局生效）</span><select id="difficulty"><option value="easy">轻松</option><option value="normal">标准</option><option value="hard">挑战</option></select></div><div class="settings-row"><span>出牌节奏</span><select id="speed"><option value="normal">沉稳</option><option value="fast">利落</option></select></div><div class="settings-row"><span>轻量音效</span><button class="toggle ${settings.sound?'on':''}" id="sound">${settings.sound?'开启':'关闭'}</button></div><p>无需联网，进度自动保存在此设备。AI 不会读取你的手牌来决策。三个难度使用不同的出牌策略，并非专业竞技 AI。</p>`);$('#difficulty').value=settings.difficulty;$('#speed').value=settings.speed;$('#difficulty').onchange=e=>{settings.difficulty=e.target.value;save('settings',settings)};$('#speed').onchange=e=>{settings.speed=e.target.value;save('settings',settings)};$('#sound').onclick=()=>{settings.sound=!settings.sound;save('settings',settings);showSettings();sound()}}
$('#history').onclick=()=>{const h=state.history||[];modal(`<div class="modal-eyebrow">TABLE JOURNAL</div><h2>牌局记录</h2>${mode==='practice'?`<div class="practice-hands">${state.hands.map((hand,i)=>`<p><strong>${names[i]} · ${hand.length} 张</strong><br>${sortHand(hand,state.level).map(cardLabel).join(' ')}</p>`).join('')}</div>`:''}<div class="history-list">${h.length?h.slice(-35).reverse().map(e=>`<div class="history-entry">${typeof e==='string'?e:formatHistory(e)}</div>`).join(''):'尚未出牌，先来一手吧。'}</div>`)};
function formatHistory(e){return `${names[e.seat]||''} ${e.type==='pass'||e.action==='pass'?'不出':e.cards?.map(cardLabel).join(' ')||e.message||e.text||'出牌'} ${e.combo?'· '+comboLabel(e.combo):''}`}
function pauseGame(){paused=true;clearTimeout(timer);persist()}function resumeGame(){paused=false;schedule()};document.addEventListener('visibilitychange',()=>document.hidden?pauseGame():resumeGame());window.addEventListener('guandan-pause',pauseGame);window.addEventListener('guandan-resume',resumeGame);window.addEventListener('pagehide',persist);window.addEventListener('resize',()=>{if(state&&!$('#game').hidden)renderHand()});statsUI();const saved=read('game',null);if(saved?.state?.hands?.length===4){state=saved.state;mode=saved.mode||'classic';roundSaved=!!saved.roundSaved;}
