import {createGame,getLegalMoves,chooseMove,play,pass,sortHand,cardLabel,comboLabel,classify,canBeat,getTrickTimeline,getCurrentTrick} from './engine.js';
import {arrangeHand,computeHandLayout,assessSelection} from './hand-layout.js';
import {createGameAudio} from './audio.js';
const $=s=>document.querySelector(s), names=['你','小岚','阿曜 · 搭档','星野'], icons=['♠','☾','✦','◇'];
let settings={difficulty:'normal',speed:'normal',cardSize:'normal',handOrder:'rank',musicEnabled:false,effectsEnabled:false,musicVolume:.28,effectsVolume:.55,...read('settings',{})}, stats=read('stats',{rounds:0,wins:0}), match=read('match',{levels:[2,2],level:2}), state=null,mode='classic',selected=new Set(),timer=null,resultTimer=null,resultEpoch=0,toastTimer=null,hintIndex=0,auto=false,paused=false,roundSaved=false,reviewIndex=0,landscapeLocked=false,selectionMove=null,selectionHistory=[],pickerOpen=false,legalCache=null,nativePaused=false,pageAway=false;
const audio=createGameAudio(settings);
function syncAudio(){audio.configure(settings);audio.setActive(!paused&&!document.hidden&&!$('#game').hidden);$('#music').textContent=settings.musicEnabled?'♫ 开':'♫ 关';$('#music').setAttribute('aria-label',settings.musicEnabled?'关闭背景音乐':'开启背景音乐')}
function sound(kind='select'){audio.playEffect(kind)}
function userGesture(){return settings.musicEnabled||settings.effectsEnabled?audio.unlock():Promise.resolve(false)}
function rememberSelection(){selectionHistory.push({ids:[...selected],move:selectionMove});if(selectionHistory.length>30)selectionHistory.shift()}
function clearSelectionHistory(){selectionHistory=[];selectionMove=null;legalCache=null}
function legalMoves(){const key=state?`${state.moveNumber}:${state.turn}:${state.hands[0].map(c=>c.id).join(',')}:${state.trick?.combo?.key||''}`:'';if(legalCache?.key!==key)legalCache={key,moves:state?getLegalMoves(state,0):[]};return legalCache.moves}
function read(key,fallback){try{return JSON.parse(localStorage.getItem('guandan-'+key))??fallback}catch{return fallback}}
function save(key,data){try{localStorage.setItem('guandan-'+key,JSON.stringify(data))}catch{}}
function persist(){if(state)save('game',{state,mode,roundSaved});else try{localStorage.removeItem('guandan-game')}catch{}}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2300)}
function cancelResult(){clearTimeout(resultTimer);resultTimer=null;resultEpoch++}
function modal(html){pickerOpen=false;$('#modal').classList.remove('picker-modal');clearTimeout(timer);cancelResult();$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){pickerOpen=false;$('#modal').classList.remove('picker-modal');$('#modal').close();if(state&&!$('#game').hidden){renderHand();selectionLabel()}schedule()}
$('#modal-close').onclick=closeModal;$('#modal').addEventListener('close',()=>{pickerOpen=false;$('#modal').classList.remove('picker-modal');if(state&&!$('#game').hidden){renderHand();selectionLabel()}schedule()});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal()}});
function rank(r){return({11:'J',12:'Q',13:'K',14:'A',15:'小王',16:'大王'})[r]||r}
function cardHTML(c,interactive=false){const red=c.suit==='H'||c.suit==='D'||c.rank===16,wild=c.suit==='H'&&c.rank===state.level,joker=c.rank>14,suit=({H:'♥',D:'♦',S:'♠',C:'♣',J:'✦'})[c.suit];return `<${interactive?'button':'div'} class="card ${red?'red':''} ${wild?'wild':''} ${c.rank===state.level?'level':''} ${joker?'joker':''} ${selected.has(c.id)&&interactive?'selected':''}" ${interactive?`data-card="${c.id}" aria-label="${cardLabel(c)}${wild?' 逢人配':''}" aria-pressed="${selected.has(c.id)}"`:''}>${rank(c.rank)}<span class="suit">${suit}</span>${!joker?`<span class="big-suit">${suit}</span>`:''}${wild?'<span class="wild-label">百搭</span>':''}</${interactive?'button':'div'}>`}
function statsUI(){$('#resume-table').hidden=!state||!!state.result;if(state&&!state.result)$('#resume-summary').textContent=`${{classic:'经典升级',quick:'快速开局',practice:'明牌练习'}[mode]} · 打 ${rank(state.level)} · 还剩 ${state.hands[0].length} 张`;$('#stat-rounds').textContent=stats.rounds;$('#stat-wins').textContent=stats.wins;$('#stat-rate').textContent=stats.rounds?Math.round(stats.wins/stats.rounds*100)+'%':'—'}
function start(m){userGesture();cancelResult();clearSelectionHistory();mode=m;auto=false;roundSaved=false;selected.clear();hintIndex=0;state=createGame({level:m==='classic'?match.level:m==='quick'?2+Math.floor(Math.random()*13):2,difficulty:settings.difficulty,teamLevels:m==='classic'?match.levels:[2,2]});$('#lobby').hidden=true;$('#game').hidden=false;document.body?.classList.add('playing');render();persist();syncAudio();sound('deal');schedule()}
for(const btn of document.querySelectorAll('[data-mode]'))btn.onclick=()=>{if(state&&!state.result){modal('<div class="modal-eyebrow">YOUR TABLE IS WAITING</div><h2>还有一局没打完</h2><p>继续当前牌局，或放弃当前牌局重新开局。</p><button class="play-button wide" id="resume">继续牌局</button><button class="secondary wide" id="restart">开始新牌局</button>');$('#resume').onclick=()=>{userGesture();closeModal();$('#lobby').hidden=true;$('#game').hidden=false;document.body?.classList.add('playing');render();syncAudio();schedule()};$('#restart').onclick=()=>{closeModal();start(btn.dataset.mode)}}else start(btn.dataset.mode)};
function render(){if(!state)return;$('#wild-reminder').textContent='♥'+rank(state.level)+' 百搭';$('#mode-label').textContent={classic:'经典升级',quick:'快速开局',practice:'明牌练习'}[mode];$('#level-label').textContent=rank(state.level);$('#score-us').textContent=rank((state.teamLevels||match.levels)[0]);$('#score-them').textContent=rank((state.teamLevels||match.levels)[1]);$('#auto').textContent='托管 '+(auto?'开':'关');for(const seat of [1,2,3]){const place=state.finished.indexOf(seat),el=$('#seat-'+seat);el.classList.toggle('active',state.turn===seat&&!state.result);el.innerHTML=`<div class="avatar">${icons[seat]}${state.turn===seat&&!state.result?'<span class="thinking-dots">•••</span>':''}</div><div class="seat-name">${names[seat]}<small>${seat===2?'我的搭档':'对手'}</small><span class="remaining ${place>=0?'finish-badge':''}">${place>=0?['头游','二游','三游','末游'][place]:state.hands[seat].length+' 张'}</span></div>`}renderTrick();const mine=state.turn===0&&!state.result&&!auto;$('#game').classList.toggle('your-turn',mine);$('#table-status').textContent=state.result?'本局结束 · 查看结算，再来一局':auto?'托管中 · 点击「托管 开」可随时接手':mine?(state.trick?(legalMoves().length?'轮到你 · 压过'+(state.trick.seat===2?'搭档':names[state.trick.seat])+'，或选择不出':'没有能接的牌 · 点击「不出」'):'自由领出 · 选一手牌开始本轮'):names[state.turn]+' 正在出牌';$('#turn-status').textContent=state.finished.includes(0)?'已出完 · 观战中':state.turn===0?'● 轮到你':'';$('#hand-count').textContent=state.hands[0].length+' 张';renderHand();$('#pass').disabled=!mine||!state.trick;$('#pass').title=!state.trick?'自由领出时必须出牌':'';$('#hint').disabled=!mine;$('#hint').textContent=hintIndex?'换个提示':'提示';$('#play').innerHTML=state.result?'查看结算':'出牌';$('#sort').disabled=state.hands[0].length===0;$('#expand-hand').disabled=state.hands[0].length===0;selectionLabel()}
function cardSelection(id){if(state?.result||auto)return;userGesture();rememberSelection();selectionMove=null;selected.has(id)?selected.delete(id):selected.add(id);for(const b of document.querySelectorAll('[data-card]')){b.classList.toggle('selected',selected.has(b.dataset.card));b.setAttribute('aria-pressed',selected.has(b.dataset.card))}selectionLabel();if(pickerOpen)pickerStatus();sound('select')}
function renderHand(){
 document.body?.classList.toggle('large-cards',settings.cardSize==='large');
 const cards=arrangeHand(state.hands[0],state.level,settings.handOrder),hand=$('#hand');
 const layout=computeHandLayout(cards.length,hand.clientWidth||window.innerWidth,window.innerHeight,settings.cardSize==='large');
 hand.classList.toggle('grouped',settings.handOrder==='group');
 hand.style.setProperty('--card-width',layout.cardWidth+'px');hand.style.setProperty('--card-step',layout.step+'px');hand.style.setProperty('--row-width',layout.rowWidth+'px');hand.classList.toggle('scrollable',layout.scrollable);hand.dataset.scrollable=String(layout.scrollable);
 $('#sort').textContent=({rank:'点数排序',group:'同点分组',suit:'花色排序'})[settings.handOrder]+' ⇅';
 if(settings.handOrder==='group'){
  const groups=[];for(const c of cards){let g=groups[groups.length-1];if(!g||g[0].rank!==c.rank||g.length===3)groups.push(g=[]);g.push(c)}
  hand.innerHTML='<div class="hand-groups">'+groups.map(g=>'<div class="rank-stack">'+g.map((c,i)=>'<div class="stack-slot" style="--stack-index:'+i+'">'+cardHTML(c,true)+'</div>').join('')+'</div>').join('')+'</div>';
 }else{
  let html='';for(let i=0;i<cards.length;i+=layout.perRow)html+='<div class="hand-row">'+cards.slice(i,i+layout.perRow).map(c=>cardHTML(c,true)).join('')+'</div>';hand.innerHTML=html||'<div class="hand-empty">手牌已出完 · 为搭档加油</div>';
 }
 for(const b of document.querySelectorAll('[data-card]'))b.onclick=()=>cardSelection(b.dataset.card);
}

function selectionAssessment(){return assessSelection(state.hands[0].filter(c=>selected.has(c.id)),state.level,state.trick?.combo,selectionMove?.combo)}
function selectionLabel(){
 if(!state)return;const a=selectionAssessment(),mine=state.turn===0&&!state.result&&!auto,n=selected.size,el=$('#selection-status');
 $('#play').disabled=!state.result&&(!mine||!a.valid);$('#clear').disabled=n===0;$('#undo').disabled=selectionHistory.length===0;
 el.classList.toggle('valid',a.valid);el.classList.toggle('invalid',!!n&&!a.valid);
 if(!n)el.textContent=auto?'正在自动出牌':settings.handOrder==='group'?'左右滑动看分组 · 点牌选择':$('#hand').dataset.scrollable==='true'?'左右滑动看余牌 · 可展开大牌选择':'点牌选中 · 也可展开大牌选择';
 else el.textContent=`已选 ${n} 张 · ${a.combo?comboLabel(a.combo):'暂不成牌'}${!mine?' · 等轮到你再出':a.valid?' · 可以出牌':a.reason==='too-small'?' · 压不过桌面':' · 请调整组合'}`;
}
function pickerStatus(){const a=selectionAssessment();$('#picker-status').textContent=$('#selection-status').textContent;$('#picker-play').disabled=state.turn!==0||auto||!a.valid;$('#picker-clear').disabled=!selected.size}
function showPicker(){
 modal(`<div class="modal-eyebrow">大牌选牌</div><h2>每张牌，看清再选</h2><p class="picker-tip">点击牌面选择或取消，选好后可直接出牌。</p><div class="picker-grid" id="picker-grid"></div><div class="picker-footer"><p id="picker-status"></p><div><button class="secondary" id="picker-clear">清空</button><button class="secondary" id="picker-done">选好了</button><button class="play-button" id="picker-play">出这手牌</button></div></div>`);
 pickerOpen=true;$('#modal').classList.add('picker-modal');$('#picker-grid').innerHTML=arrangeHand(state.hands[0],state.level,settings.handOrder).map(c=>cardHTML(c,true)).join('');
 for(const b of document.querySelectorAll('[data-card]'))b.onclick=()=>cardSelection(b.dataset.card);
 $('#picker-clear').onclick=()=>{rememberSelection();selected.clear();selectionMove=null;for(const b of document.querySelectorAll('[data-card]')){b.classList.remove('selected');b.setAttribute('aria-pressed','false')}selectionLabel();pickerStatus()};
 $('#picker-done').onclick=closeModal;$('#picker-play').onclick=()=>{const ids=[...selected],declaration=selectionMove?.combo;closeModal();move(ids,declaration)};pickerStatus();
}
$('#expand-hand').onclick=showPicker;

function move(ids,declaration=null){try{const actor=state.turn;play(state,state.turn,ids,declaration);sound(['bomb','straightFlush','jokerBomb'].includes(state.trick?.combo?.type)?'bomb':'play');if(actor===0){selected.clear();clearSelectionHistory()}else{selectionMove=null;legalCache=null}hintIndex=0;render();persist();afterMove()}catch(e){sound('error');toast(e.message||'这手牌暂时不能出')}}
function passTurn(){try{const seat=state.turn;pass(state,seat);sound('pass');if(seat===0){selected.clear();clearSelectionHistory()}else{selectionMove=null;legalCache=null}hintIndex=0;render();toast(state.lastAction?.trickClosed?('本轮结束 · '+names[state.turn]+(state.lastAction.partnerLead?' 接风领出':' 重新领出')):names[seat]+'：不出');persist();afterMove()}catch(e){toast(e.message)}}
function queueResult(){cancelResult();if(!state?.result||paused||document.hidden||$('#game').hidden||$('#modal').open)return;const completed=state,epoch=resultEpoch;resultTimer=setTimeout(()=>{if(epoch!==resultEpoch)return;resultTimer=null;if(state===completed&&!paused&&!document.hidden&&!$('#game').hidden&&!$('#modal').open)showResult()},600)}
function afterMove(){if(state.result){clearTimeout(timer);settleRound();queueResult()}else schedule()}
function schedule(){clearTimeout(timer);if(paused||document.hidden||$('#modal').open||$('#game').hidden||!state||state.result)return;if(state.turn===0&&!auto)return;timer=setTimeout(()=>{if(paused||$('#modal').open||!state||state.result)return;try{const m=chooseMove(state,state.turn);if(m)move(m.ids,m.combo);else passTurn()}catch(e){console.error(e);toast('牌局发生异常，请返回大厅重新开局')}},settings.speed==='fast'?650:settings.speed==='slow'?1900:1300)}
$('#play').onclick=()=>{userGesture();state?.result?showResult():move([...selected],selectionMove?.combo)};$('#pass').onclick=()=>{userGesture();passTurn()};$('#clear').onclick=()=>{rememberSelection();selected.clear();selectionMove=null;renderHand();selectionLabel()};
$('#undo').onclick=()=>{const previous=selectionHistory.pop();if(!previous)return;selected=new Set(previous.ids.filter(id=>state.hands[0].some(c=>c.id===id)));selectionMove=previous.move;renderHand();selectionLabel()};
$('#hint').onclick=()=>{userGesture();const moves=legalMoves();if(!moves.length)return toast('没有能接的牌，可以选择不出');rememberSelection();const m=moves[hintIndex++%moves.length];selectionMove=m;selected=new Set(m.ids);render();sound('select')};
$('#sort').onclick=()=>{const orders=['rank','group','suit'];settings.handOrder=orders[(orders.indexOf(settings.handOrder)+1)%orders.length];save('settings',settings);renderHand();selectionLabel()};
$('#auto').onclick=()=>{userGesture();auto=!auto;selected.clear();clearSelectionHistory();render();schedule();toast(auto?'已托管，再点一次就能接手':'已接手，轮到你时可出牌')};
$('#home').onclick=()=>{clearTimeout(timer);cancelResult();persist();$('#game').hidden=true;$('#lobby').hidden=false;document.body?.classList.remove('playing');syncAudio();statsUI()};
$('#resume-table').onclick=()=>{userGesture();$('#lobby').hidden=true;$('#game').hidden=false;document.body?.classList.add('playing');render();syncAudio();schedule()};
$('#music').onclick=async()=>{settings.musicEnabled=!settings.musicEnabled;save('settings',settings);syncAudio();if(settings.musicEnabled){const available=await userGesture();if(settings.musicEnabled)toast(available?'轻音乐已开启 · 设置里可单独调音量':'此设备暂时无法播放声音，牌局仍可继续')}else toast('背景音乐已关闭')};

function settleRound(){if(!state?.result||roundSaved)return;const r=state.result;stats.rounds++;if(r.winnerTeam===0)stats.wins++;save('stats',stats);if(mode==='classic'){match=r.matchWon?{levels:[2,2],level:2}:{levels:r.teamLevels||state.teamLevels,level:r.nextLevel};save('match',match)}roundSaved=true;persist();statsUI()}
function showResult(){if(!state?.result)return;settleRound();const r=state.result,win=r.winnerTeam===0;sound(win?'win':'lose');modal(`<div class="modal-eyebrow">ROUND COMPLETE</div><div class="result-icon">${win?'✦':'♠'}</div><h2 class="result-title">${win?'默契制胜！':'再来，下一局！'}</h2><p style="text-align:center">${win?'你与阿曜赢下本局':'小岚与星野赢下本局'} · 升 ${r.upgrade} 级</p><div class="result-ranks">${r.order.map((s,i)=>`<div><b>${r.tiedLast?.includes(s)?'双下': ['头游','二游','三游','末游'][i]}</b>${names[s]}</div>`).join('')}</div><p>${mode==='classic'?`${r.matchWon?'打过 A，本场升级赛完成！下一场从 2 开始。':'下一局打 '+rank(r.nextLevel)+'。'}休闲升级模式不进行进贡、还贡。`:'换副牌，再试试新的配合。'}</p><button class="play-button wide" id="next-round">再来一局 ↗</button><button class="secondary wide" id="back-lobby">返回大厅</button>`);$('#next-round').onclick=()=>{closeModal();start(mode)};$('#back-lobby').onclick=()=>{closeModal();state=null;persist();$('#game').hidden=true;$('#lobby').hidden=false;document.body?.classList.remove('playing');syncAudio();statsUI()}}
function showHelp(){modal(`<div class="modal-eyebrow">3 步上手</div><h2>和对面的阿曜，一起赢</h2><div class="guide-step"><b>1</b><div><h3>先选牌，再出牌</h3><p>点击牌面选中。牌型合法且能压过桌面时，「出牌」才会亮起。牌太密？点「展开选牌」。</p><div class="guide-cards">A♠ A♥ <span>对子</span>　7♠ 7♥ 7♣ 8♠ 8♥ <span>三带二</span></div></div></div><div class="guide-step"><b>2</b><div><h3>接不上，也可以不出</h3><p>跟牌要同类型、同张数并且更大。点「提示」会选好一手，再点可换一个建议；不会替你出牌。自由领出时不能不出。</p></div></div><div class="guide-step"><b>3</b><div><h3>帮搭档先出完</h3><p>你和阿曜同队，拿到头游就赢。搭档二游升 3 级、三游升 2 级、末游升 1 级。红桃级牌是百搭，但不能代替王。</p></div></div><details><summary>支持的牌型与大小</summary><p>单张、对子、三张、三带二；5 张顺子、3 连对、2 连三张（钢板）；4 张以上同点数炸弹、同花顺、四王炸。</p><p>级牌高于 A，小王和大王更大。顺子按自然点数，A 可在最小或最大端，不能绕回。炸弹压普通牌；同花顺压 5 张及以下炸弹，低于 6 张及以上炸弹；四王炸最大。</p></details><details><summary>接风、升级与休闲规则</summary><p>其余有效玩家都不出，本轮最后出牌者重新领出；若已出完，仍有牌的搭档接风。A 必须实打，打 A 时搭档进前三即可通关并重置为 2。</p><p>本版为离线休闲升级，不含进贡、还贡、抗贡及连续三次不过 A 退级，不支持真人联网。</p></details><details><summary>音乐、存档和练习</summary><p>背景音乐和音效默认关闭，点击 ♫ 或在设置中开启；各自音量单独保存。切到后台会暂停。返回大厅会保存当前牌局。「明牌练习」可在记录中查看四家手牌。</p></details>`)}
$('#help').onclick=showHelp;$('#quick-guide').onclick=showHelp;$('#table-help').onclick=showHelp;
$('#settings').onclick=showSettings;$('#game-settings').onclick=showSettings;
function showSettings(){modal(`<div class="modal-eyebrow">牌桌设置</div><h2>打得舒服，最重要</h2><div class="settings-row"><label for="difficulty">AI 难度 <small>下局生效</small></label><select id="difficulty"><option value="easy">轻松</option><option value="normal">标准</option><option value="hard">挑战</option></select></div><div class="settings-row"><label for="speed">出牌节奏</label><select id="speed"><option value="slow">慢慢打</option><option value="normal">舒适</option><option value="fast">快速</option></select></div><div class="settings-row"><label for="card-size">手牌字号</label><select id="card-size"><option value="normal">标准</option><option value="large">大字</option></select></div><div class="settings-row"><span>背景音乐<small>原创轻松旋律 · 离线播放</small></span><button class="toggle ${settings.musicEnabled?'on':''}" id="music-toggle">${settings.musicEnabled?'开启':'关闭'}</button></div><div class="volume-row"><label for="music-volume">音乐音量</label><input id="music-volume" type="range" min="0" max="100" step="5" value="${Math.round(settings.musicVolume*100)}"><output id="music-value">${Math.round(settings.musicVolume*100)}%</output></div><div class="settings-row"><span>操作音效<small>选牌、出牌、炸弹、结算</small></span><button class="toggle ${settings.effectsEnabled?'on':''}" id="sound">${settings.effectsEnabled?'开启':'关闭'}</button></div><div class="volume-row"><label for="effect-volume">音效音量</label><input id="effect-volume" type="range" min="0" max="100" step="5" value="${Math.round(settings.effectsVolume*100)}"><output id="effect-value">${Math.round(settings.effectsVolume*100)}%</output></div><p>声音只会在你开启后播放，切到后台自动暂停。AI 只读自己的牌和公开信息；提示是合法建议，不代表最佳打法。</p>`);
 $('#card-size').value=settings.cardSize;$('#card-size').onchange=e=>{settings.cardSize=e.target.value;save('settings',settings);if(state)renderHand()};$('#difficulty').value=settings.difficulty;$('#speed').value=settings.speed;$('#difficulty').onchange=e=>{settings.difficulty=e.target.value;save('settings',settings)};$('#speed').onchange=e=>{settings.speed=e.target.value;save('settings',settings)};
 const toggle=(id,key)=>{$(id).onclick=()=>{settings[key]=!settings[key];save('settings',settings);userGesture();syncAudio();$(id).textContent=settings[key]?'开启':'关闭';$(id).classList.toggle('on',settings[key]);if(key==='effectsEnabled')sound('select')}};toggle('#sound','effectsEnabled');toggle('#music-toggle','musicEnabled');
 for(const [id,key,out] of [['music-volume','musicVolume','music-value'],['effect-volume','effectsVolume','effect-value']])$('#'+id).oninput=e=>{settings[key]=Number(e.target.value)/100;$('#'+out).textContent=e.target.value+'%';save('settings',settings);syncAudio()};
}

function renderTrick(){const round=getCurrentTrick(state);$('#played').innerHTML=`<span class="trick-number">第 ${round.number} 轮</span><span class="trick-phase">${state.trick?'跟牌':'自由领出'}</span>`;for(let seat=0;seat<4;seat++){const el=$('#play-seat-'+seat),last=round.lastActions[seat],p=round.plays[seat],winning=state.trick?.seat===seat;el.classList.toggle('winning',winning);el.style.setProperty('--played-count',p?.cards.length||1);el.classList.toggle('waiting-turn',state.turn===seat&&!state.result);el.innerHTML=`<div class="play-owner">${seat===0?'你':seat===2?'搭档':names[seat]}${winning?'<span class="lead-mark">当前最大</span>':''}${last?.type==='pass'?'<span class="pass-badge">不出</span>':''}</div>${p?`<div class="mini-hand">${p.cards.map(c=>cardHTML(c)).join('')}</div><div class="play-combo">${comboLabel(p.combo)} · ${p.cards.length} 张</div>`:'<div class="empty-play">'+(state.finished.includes(seat)?'已出完':'等待出牌')+'</div>'}`}}
function reviewTrick(index){const rounds=getTrickTimeline(state);if(!rounds.length){toast('还没有出牌记录');return}reviewIndex=Math.max(0,Math.min(index,rounds.length-1));const r=rounds[reviewIndex];modal(`<div class="modal-eyebrow">TRICK REPLAY · ${reviewIndex+1} / ${rounds.length}</div><h2>第 ${r.number} 轮回看</h2><div class="review-controls"><button class="secondary" id="review-prev" ${reviewIndex===0?'disabled':''}>上一轮</button><span>${r.closed||state.result&&reviewIndex===rounds.length-1?'已结束':'进行中'} · ${r.actions.length} 次操作</span><button class="secondary" id="review-next" ${reviewIndex===rounds.length-1?'disabled':''}>下一轮</button></div><div class="review-seats">${[2,1,3,0].map(seat=>{const p=r.plays[seat],a=r.lastActions[seat];return `<div class="review-seat ${r.winnerSeat===seat?'review-winner':''}"><strong>${names[seat]}</strong>${r.winnerSeat===seat?'<small>本轮最大</small>':''}<div>${p?p.cards.map(cardLabel).join(' '):'未出牌'}</div><em>${p?comboLabel(p.combo):''}${a?.type==='pass'?' · 不出':''}</em></div>`}).join('')}</div><h3>本轮完整顺序</h3><div class="history-list">${r.actions.map(e=>`<div class="history-entry">${formatHistory(e)}</div>`).join('')}</div>`);$('#review-prev').onclick=()=>reviewTrick(reviewIndex-1);$('#review-next').onclick=()=>reviewTrick(reviewIndex+1)}
$('#previous-trick').onclick=()=>{const rounds=getTrickTimeline(state),i=rounds.length-1,target=rounds[i]?.closed||state.result?i:i-1;if(target<0)return toast('还没有结束的一轮，可打开牌局记录查看当前轮');reviewTrick(target)};
$('#history').onclick=()=>{const rounds=getTrickTimeline(state);modal(`<div class="modal-eyebrow">TABLE JOURNAL</div><h2>整局出牌记录</h2>${mode==='practice'?`<div class="practice-hands">${state.hands.map((hand,i)=>`<p><strong>${names[i]} · ${hand.length} 张</strong><br>${sortHand(hand,state.level).map(cardLabel).join(' ')}</p>`).join('')}</div>`:''}<div class="history-list">${rounds.length?rounds.map((r,i)=>`<button class="history-round" id="round-${i}"><b>第 ${r.number} 轮</b><span>${r.actions.length} 次操作 · ${r.closed||state.result&&i===rounds.length-1?'已结束':'进行中'}</span><small>${r.winnerSeat!==null?names[r.winnerSeat]+'领出最大牌':''}</small></button>`).reverse().join(''):'尚未出牌，先来一手吧。'}</div>`);rounds.forEach((r,i)=>$('#round-'+i).onclick=()=>reviewTrick(i))};
function formatHistory(e){return `${names[e.seat]||''} ${e.type==='pass'?'不出':e.cards?.map(cardLabel).join(' ')||'出牌'} ${e.combo?'· '+comboLabel(e.combo):''}${e.trickClosed?' · 本轮结束':''}`}
$('#history-top').onclick=()=>$('#history').onclick();
$('#orientation').onclick=async()=>{landscapeLocked=!landscapeLocked;$('#orientation').textContent=landscapeLocked?'自动旋转':'横屏';if(window.location?.hostname==='appassets.androidplatform.net'){window.location.href='https://appassets.androidplatform.net/ui/'+(landscapeLocked?'landscape':'auto');return}try{if(landscapeLocked){await document.documentElement.requestFullscreen?.();if(window.screen?.orientation?.lock)await window.screen.orientation.lock('landscape');else toast('请将手机横放；此浏览器不支持锁定方向')}else{window.screen?.orientation?.unlock?.();if(document.fullscreenElement)await document.exitFullscreen?.()}}catch{toast('请开启手机自动旋转后横放，牌桌会自动适配')}};
function syncLifecycle(){paused=nativePaused||pageAway||document.hidden;if(paused){clearTimeout(timer);cancelResult();persist();syncAudio()}else{syncAudio();if(state?.result)queueResult();else schedule()}}
document.addEventListener('visibilitychange',syncLifecycle);window.addEventListener('guandan-pause',()=>{nativePaused=true;syncLifecycle()});window.addEventListener('guandan-resume',()=>{nativePaused=false;syncLifecycle()});window.addEventListener('pagehide',()=>{pageAway=true;syncLifecycle()});window.addEventListener('pageshow',()=>{pageAway=false;syncLifecycle()});window.addEventListener('resize',()=>{if(state&&!$('#game').hidden){renderHand();selectionLabel()}});statsUI();const saved=read('game',null);if(saved?.state?.hands?.length===4){state=saved.state;mode=saved.mode||'classic';roundSaved=!!saved.roundSaved;settleRound();}statsUI();syncAudio();
