import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import * as engine from '../engine.js';
const code=fs.readFileSync(new URL('../game.js',import.meta.url),'utf8').replace(/^import[^\n]+\n/,'');
function harness(storage=new Map(),width=390,height=844){
 const nodes=new Map(),events={},tasks=new Map();let next=1;
 const classes=()=>{const set=new Set();return{add:n=>set.add(n),remove:n=>set.delete(n),contains:n=>set.has(n),toggle(n,v){v=v??!set.has(n);v?set.add(n):set.delete(n)}}};
 function node(id){if(!nodes.has(id)){const n={id,hidden:id==='game',open:false,disabled:false,textContent:'',dataset:{},style:{setProperty(){}},classList:classes(),events:{},clientWidth:width-16,addEventListener(t,f){this.events[t]=f},setAttribute(){},getBoundingClientRect(){return{x:0,y:0,left:0,top:0,right:400,bottom:800}},showModal(){this.open=true},close(){this.open=false;this.events.close?.()}};let html='';Object.defineProperty(n,'innerHTML',{get:()=>html,set:v=>{html=v;for(const m of v.matchAll(/id="([^"]+)"/g))node(m[1]);if(id==='hand'){for(const k of [...nodes.keys()])if(k.startsWith('card:'))nodes.delete(k);for(const m of v.matchAll(/data-card="([^"]+)"/g)){const c=node('card:'+m[1]);c.dataset.card=m[1]}}}});nodes.set(id,n)}return nodes.get(id)}
 ['classic','quick','practice'].forEach(m=>{node('mode:'+m).dataset.mode=m});
 const document={hidden:false,querySelector:s=>node(s.slice(1)),querySelectorAll:s=>s==='[data-mode]'?[...nodes.values()].filter(n=>n.dataset.mode):s==='[data-card]'?[...nodes.values()].filter(n=>n.dataset.card):[],addEventListener:(t,f)=>events[t]=f};
 const window={innerWidth:width,innerHeight:height,addEventListener:(t,f)=>events[t]=f};
 const sandbox={...engine,console,Math,Set,JSON,document,window,localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},setTimeout:(fn,ms)=>{const id=next++;tasks.set(id,{fn,ms});return id},clearTimeout:id=>tasks.delete(id)};
 vm.createContext(sandbox);vm.runInContext(code+';globalThis.inspect=()=>({state,mode,selected,paused,auto,match,stats});globalThis.startGame=start;globalThis.showResults=showResult;',sandbox);
 return{sandbox,node,events,tasks,storage,click:id=>{const n=node(id);if(!n.disabled)n.onclick?.({target:n})},tick(){const item=[...tasks].find(([,t])=>t.ms===450||t.ms===950||t.ms===600);if(!item)return false;tasks.delete(item[0]);item[1].fn();return true}};
}
test('mobile modes, hints, legal play, history, settings, save and restore',()=>{for(const size of [[320,568],[390,844],[844,390],[1280,900]]){const h=harness(new Map(),...size);h.click('mode:classic');let s=h.sandbox.inspect().state;assert.equal(s.hands[0].length,27);assert.equal(h.node('game').hidden,false);h.click('hint');assert.ok(h.sandbox.inspect().selected.size>0);h.click('play');assert.ok(s.hands[0].length<27);const saved=JSON.parse(h.storage.get('guandan-game'));assert.equal(saved.state.moveNumber,1);h.click('history');assert.equal(h.node('modal').open,true);assert.match(h.node('modal-content').innerHTML,/牌局记录/);h.click('modal-close');h.click('settings');assert.match(h.node('modal-content').innerHTML,/AI 难度/);h.click('sound');h.click('modal-close');h.click('home');const restored=harness(h.storage,...size);restored.click('mode:quick');assert.equal(restored.node('modal').open,true);restored.click('resume');assert.equal(restored.sandbox.inspect().state.moveNumber,1);assert.equal(restored.node('game').hidden,false)}});
test('autoplay finishes real rounds, result is idempotent and replay starts fresh',()=>{for(const mode of ['classic','quick','practice']){const h=harness();h.click('mode:'+mode);h.click('auto');let ticks=0;while(!h.sandbox.inspect().state.result&&h.tick()){if(++ticks>600)throw Error('UI round failed to finish')}assert.ok(h.sandbox.inspect().state.result);h.tick();assert.equal(h.node('modal').open,true);assert.equal(h.sandbox.inspect().stats.rounds,1);h.sandbox.showResults();assert.equal(h.sandbox.inspect().stats.rounds,1);h.click('next-round');assert.equal(h.sandbox.inspect().state.result,null);assert.equal(h.sandbox.inspect().state.hands[0].length,27);assert.equal(h.sandbox.inspect().auto,false)}});
test('pause, help modal, and lobby suspend AI, resume schedules once',()=>{const h=harness();h.click('mode:classic');h.click('auto');h.events['guandan-pause']();assert.equal(h.sandbox.inspect().paused,true);assert.equal(h.tick(),false);h.events['guandan-resume']();assert.equal([...h.tasks.values()].filter(t=>t.ms===950).length,1);h.click('help');assert.equal(h.tick(),false);h.click('modal-close');assert.equal([...h.tasks.values()].filter(t=>t.ms===950).length,1);h.click('home');assert.equal(h.tick(),false)});
test('A match clears to 2 and double-down ranks are honest',()=>{const h=harness();h.click('mode:classic');const s=h.sandbox.inspect().state;s.result={winnerTeam:0,order:[0,2,1,3],upgrade:3,teamLevels:[14,2],nextLevel:14,matchWon:true,tiedLast:[1,3]};s.turn=null;h.sandbox.showResults();assert.equal(h.sandbox.inspect().match.level,2);assert.equal((h.node('modal-content').innerHTML.match(/双下/g)||[]).length,2);h.click('next-round');assert.equal(h.sandbox.inspect().state.level,2)});
